植木鉢・額縁の破壊を鯖民が出来ないように
AzisabaNetwork/AzisabaLobby pull request #1
Opened 2021-12-01 06:41 UTC by merunno

### description

アジ鯖のロビーで植木鉢・額縁を破壊することが出来なくします。

### permission

- `azisabalobby-allow-flower-pot`
  - Permissions related to the destruction of flowerpots.
  - default: `op`
- `azisabalobby-allow-picture-frame`
  - Permissions related to the destruction of picture frames.
  - default: `op`

2021-12-01 06:55 UTC, acrylic-style requested changes

2021-12-01 06:55 UTC, acrylic-style commented on src/main/resources/plugin.yml
> +    description: 額縁の破壊に関するパーミッションです。
```suggestion
permissions:
  azisabalobby.allow-flower-pot:
    default: op
    description: 植木鉢の破壊に関するパーミッションです。
  azisabalobby.allow-picture-frame:
    default: op
    description: 額縁の破壊に関するパーミッションです。
```
もしくは削除

2021-12-01 06:55 UTC, acrylic-style commented on README.md
> +  - default: `op`
```suggestion
- `azisabalobby.allow-flower-pot`
  - Permissions related to the destruction of flowerpots.
  - default: `op`
- `azisabalobby.allow-picture-frame`
  - Permissions related to the destruction of picture frames.
  - default: `op`
- `azisabalobby.allow-creative-mode`
  - Whether the player is allowed to be in creative mode.
  - default: `op`
- `azisabalobby.allow-survival-mode`
  - Whether the player is allowed to be in survival mode.
  - default: `op`
- `azisabalobby.allow-spectator-mode`
  - Whether the player is allowed to be in spectator mode.
  - default: `op`
- `azisabalobby.allow-flight`
  - Whether the player is allowed to fly.
  - default: `op`
```

2021-12-01 06:55 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            if(damager.hasPermission("azisabalobby.allow-picture-frame")) return;
`allow-picture-frame` → `allow-destroy-painting`

2021-12-01 06:55 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/FlowerPotProtectionListener.java
> +        if(player.hasPermission("azisabalobby.allow-flower-pot")) return;
`allow-interact-flower-pot`のほうがいいかも

2021-12-01 06:55 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/FlowerPotProtectionListener.java
> +        e.setCancelled(true);
どのブロックにInteractしたかのチェックが必要

2021-12-01 06:55 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
どのブロックにInteractしたかのチェックが必要

2021-12-03 07:01 UTC, merunno commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
アイテムの取得が `EntityDamageByEntityEvent` から出来ないんですが、どういう処理になりますか.....?

2021-12-03 07:02 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
`e.getEntity() instanceof Painting`みたいなやつがあるはず

2021-12-03 07:07 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/FlowerPotProtectionListener.java
> +        if(item != null) {
e.getBlock()をnullチェックしたあとにgetType() == FLOWER_POTみたいなもの

2021-12-03 07:13 UTC, merunno commented
こんな感じですかね....

2021-12-03 07:15 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/FlowerPotProtectionListener.java
> +        if(item != null) {
アイテムではない。e.getItem()はプレイヤーが右もしくは左クリックしたときに持っていたアイテム。
e.getBlock()はクリックしたブロック

2021-12-03 07:19 UTC, merunno commented on src/main/java/net/azisaba/lobby/listeners/FlowerPotProtectionListener.java
> +        if(item != null) {
![image](https://user-images.githubusercontent.com/82575685/144561466-ea1b0e46-bda2-496f-865a-e956b50b534d.png)

取得がないんですよね

2021-12-03 07:20 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/FlowerPotProtectionListener.java
> +        if(item != null) {
e.getClickedBlock()

2021-12-03 07:29 UTC, merunno commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
![image](https://user-images.githubusercontent.com/82575685/144562588-f60fb315-d771-4769-90fe-c714ce4ed277.png)
だめですね.........

2021-12-03 07:34 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
言い方が悪かった
```java
if (entity instanceof Painting) e.setCancelled(true);
```

2021-12-03 07:56 UTC, merunno commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
🙏

2021-12-03 07:58 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
この行はいらないので削除

2021-12-03 08:01 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
githubの表示の都合上4行に見えるけど1行です

2021-12-03 08:42 UTC, merunno commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
OH.... 何行目でしょう

2021-12-03 09:00 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +            e.setCancelled(true);
17 (一番下)

2021-12-03 09:25 UTC, acrylic-style requested changes
私がアホすぎて額縁を完全に忘れてたのと雪玉で壊せるの忘れてたのでこれだけやってほしい

2021-12-03 09:25 UTC, acrylic-style commented on src/main/java/net/azisaba/lobby/listeners/HangingProtectionListener.java
> +        }
```suggestion
        Entity damager = e.getDamager();
        if (damager instanceof Player) {
            if (damager.hasPermission("azisabalobby.allow-destroy-painting")) return;
        }
        Entity entity = e.getEntity();
        if (entity instanceof Painting || entity instanceof ItemFrame) e.setCancelled(true);
```

2021-12-03 10:24 UTC, acrylic-style approved these changes

2021-12-03 10:56 UTC, merged